// export const API_SERVER = 'http://toan.ngrok.com';
export const API_SERVER = 'http://54.255.201.98';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const RETRIEVE_TOKEN_SUCCESS = 'RETRIEVE_TOKEN_SUCCESS';
export const RETRIEVE_TOKEN_FAIL = 'RETRIEVE_TOKEN_FAIL';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_TOKEN_FAIL = 'SET_TOKEN_FAIL';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_TODAY_ACTIVITY = 'GET_TODAY_ACTIVITY';
export const GET_TODAY_ACTIVITY_SUCCESS = 'GET_TODAY_ACTIVITY_SUCCESS';
export const GET_TODAY_ACTIVITY_FAIL = 'GET_TODAY_ACTIVITY_FAIL';
export const START_ACTIVITY = 'START_ACTIVITY';
export const START_ACTIVITY_SUCCESS = 'START_ACTIVITY_SUCCESS';
export const START_ACTIVITY_FAIL = 'START_ACTIVITY_FAIL';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_FAIL = 'SUBMIT_ANSWER_FAIL';
