export const SET_ENTRIES = 'SET_ENTRIES';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const RETRIEVE_TOKEN_SUCCESS = 'RETRIEVE_TOKEN_SUCCESS';
export const RETRIEVE_TOKEN_FAIL = 'RETRIEVE_TOKEN_FAIL';

export const GET_TODAY_ACTIVITY = 'GET_TODAY_ACTIVITY';
export const GET_TODAY_ACTIVITY_SUCCESS = 'GET_TODAY_ACTIVITY_SUCCESS';
export const GET_TODAY_ACTIVITY_FAIL = 'GET_TODAY_ACTIVITY_FAIL';
